# Generated by Django 5.0 on 2024-01-02 15:15

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('majors', '0001_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+000000000000', max_length=30, region=None, verbose_name='Phone number')),
                ('about_me', models.TextField(default='Something about yourself...', verbose_name='About me')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=31, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(default='AZ', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Baku', max_length=127, verbose_name='City')),
                ('education_language', models.CharField(choices=[('AZE', 'Azerbaijani'), ('RUS', 'Russian'), ('ENG', 'English'), ('FR', 'French'), ('OTHER', 'Other')], default='AZE', help_text='Main language of education', max_length=255, verbose_name='Language of education')),
                ('year_of_study', models.IntegerField(blank=True, default=1, null=True, verbose_name='Year of study')),
                ('degree_type', models.CharField(blank=True, choices=[('Bch', "Bachelor's degree"), ('Ms', "Masters's degree"), ('PHD', 'PHD')], help_text='Bachelors, Masters, PHD ...', max_length=255, null=True, verbose_name='Type of degree')),
                ('is_student', models.BooleanField(default=False, help_text='Are you a student', verbose_name='Student')),
                ('is_teacher', models.BooleanField(default=False, help_text='Are you a teacher?', verbose_name='Teacher')),
                ('is_other', models.BooleanField(default=False, help_text='You are neither teacher nor student', verbose_name='Other')),
                ('top_helper', models.BooleanField(default=False, verbose_name='Top helper')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of reviews')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='major', to='majors.major')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='university', to='universities.university')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
