# Generated by Django 5.0 on 2024-01-02 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='university', to='universities.university'),
        ),
    ]
