# Generated by Django 5.0 on 2024-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('Bachelor', "Bachelor's degree"), ('Masters', "Masters's degree"), ('PHD', 'PHD')], help_text='Bachelors, Masters, PHD ...', max_length=255, null=True, verbose_name='Type of degree'),
        ),
    ]
