version: "3.9"

services:
  api:
    build: 
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: gunicorn learning_union.wsgi --bind 0.0.0.0:8001 && python manage.py migrate --no-input && python manage.py collectstatic --no-input
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    ports:
      - "8001:8001"
    depends_on:
      - db  
    env_file:
      - .env
    networks:
      - lu-react    

  db:
    image: mysql
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_NAME}
    networks:
      - lu-react

networks:
  lu-react:
    driver: bridge

volumes:
  static_volume:
  media_volume: