# Generated by Django 5.0 on 2024-01-02 15:15

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='University Name')),
                ('short_name', models.CharField(blank=True, max_length=15, null=True, verbose_name='Sort name of the University(if exists)')),
                ('date_created', models.DateField(verbose_name='Date of creation')),
                ('country', django_countries.fields.CountryField(default='AZ', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Baku', max_length=127, verbose_name='City')),
                ('address', models.CharField(max_length=255, verbose_name='Address of the university')),
                ('num_teachers', models.IntegerField(default=0, verbose_name='Number of teachers in the university')),
                ('num_students', models.IntegerField(default=0, verbose_name='Number of students in the university')),
                ('head_organization', models.CharField(blank=True, max_length=127, null=True, verbose_name='Head organization(if exists)')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+000000000000', max_length=30, region=None, verbose_name='Phone number')),
                ('rector', models.CharField(max_length=127, verbose_name='Rector o the university')),
                ('website', models.CharField(blank=True, max_length=127, null=True, verbose_name='Website of the university(if exists)')),
                ('description', models.TextField(verbose_name='Description')),
                ('international_ranking', models.IntegerField(blank=True, null=True, verbose_name='International ranking(if exists)')),
                ('local_ranking', models.IntegerField(blank=True, null=True, verbose_name='Local ranking(if exists)')),
                ('num_students_registered', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of students registered from this university')),
                ('num_teachers_registered', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of teachers registered from this university')),
                ('activity_lvl', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very good'), (5, 'Excellent')], default=0, help_text='1=Poor, 2=Fair, 3=Good, 4=Very good, 5=excellent', verbose_name='Activity level of the university on the website')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
