# Generated by Django 5.0 on 2024-01-02 18:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Title of the question')),
                ('short_description', models.CharField(max_length=127, verbose_name='Brief description of the question')),
                ('details', models.TextField(verbose_name='Details of the question')),
                ('subject', models.CharField(max_length=127, verbose_name='Subject from which the problem arose')),
                ('num_views', models.IntegerField(default=0, verbose_name='Number of views on a question')),
                ('num_answers', models.IntegerField(default=0, verbose_name='Number of answers on a question')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 1(Optional)')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 2(Optional)')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 3(Optional)')),
                ('date_asked', models.DateTimeField(default=datetime.datetime(2024, 1, 2, 18, 18, 22, 692003, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Date asked')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date of last modification')),
                ('date_last_view', models.DateTimeField(default=datetime.datetime(2024, 1, 2, 18, 18, 22, 692171, tzinfo=datetime.timezone.utc), verbose_name='Date of last view')),
                ('solved_status', models.BooleanField(default=False, verbose_name='Solution status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile', verbose_name='An author of the question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
