# Generated by Django 5.0.1 on 2024-01-06 10:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=63, verbose_name='Title of the question')),
                ('short_description', models.CharField(max_length=127, verbose_name='Brief description of the question')),
                ('details', models.TextField(verbose_name='Details of the question')),
                ('subject', models.CharField(max_length=127, verbose_name='Subject from which the problem arose')),
                ('num_views', models.IntegerField(default=0, verbose_name='Number of views on a question')),
                ('num_answers', models.IntegerField(default=0, verbose_name='Number of answers on a question')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 1(Optional)')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 2(Optional)')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 3(Optional)')),
                ('date_asked', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date asked')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date of last modification')),
                ('date_last_view', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of last view')),
                ('solved_status', models.BooleanField(default=False, verbose_name='Solution status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active status')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile', verbose_name='An author of the question')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionViews',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=255, verbose_name='IP Address')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_views', to='questions.question')),
            ],
            options={
                'verbose_name': 'Total views',
                'verbose_name_plural': 'Total views',
            },
        ),
    ]
