# Generated by Django 5.0 on 2024-01-05 12:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_date_asked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionViews',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=255, verbose_name='IP Address')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_views', to='questions.question')),
            ],
            options={
                'verbose_name': 'Total views',
                'verbose_name_plural': 'Total views',
            },
        ),
    ]
