# Generated by Django 5.0 on 2024-01-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the major')),
                ('num_students', models.IntegerField(default=0, verbose_name='Number of students with this major')),
            ],
        ),
    ]
