# Generated by Django 5.0 on 2024-01-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'verbose_name': 'Major', 'verbose_name_plural': 'Majors'},
        ),
    ]
