# Generated by Django 5.0.1 on 2024-01-06 10:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=63, verbose_name='Title of the answer')),
                ('description', models.TextField(verbose_name='Description of the solution')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 3')),
                ('date_answered', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date answered')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date of last modification')),
                ('is_solution', models.BooleanField(default=False, verbose_name='Is solution')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
