# Generated by Django 5.0 on 2024-01-02 18:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0004_alter_profile_options'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63, verbose_name='Title of the answer')),
                ('description', models.TextField(verbose_name='Description of the solution')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image 3')),
                ('date_answered', models.DateTimeField(default=datetime.datetime(2024, 1, 2, 18, 18, 22, 693089, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Date answered')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date of last modification')),
                ('is_solution', models.BooleanField(default=False, verbose_name='Is solution')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile', verbose_name='An author of the answer')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.question', verbose_name='The question that is being answered')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
