# Generated by Django 5.0 on 2024-01-02 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_answered',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date answered'),
        ),
    ]
